# Asteroids
"Nickel Ore":
  type: "Ore"
  weight: 1
  price: 9
"Iron Ore":
  type: "Ore"
  weight: 1
  price: 9
"Cobalt Ore":
  type: "Ore"
  weight: 1
  price: 9
"Septarium":
  type: "Ore"
  weight: 1
  price: 9
"Titanium Ore":
  type: "Ore"
  weight: 1
  price: 20
"Tryon Ore":
  type: "Ore"
  weight: 1
  price: 40
"Lunarium Ore":
  type: "Ore"
  weight: 1
  price: 200

# Equipment
"Gatling Laser":
  type: "Weapon"
  weight: 4
  damage: 5
  slot_type: "main"
  crafting: {"asteroid.nickel_ore": 5, "asteroid.cobalt_ore": 10, "materials.laser_diodes": 1}
  crafting_duration: 10
  price: 120
"Try Pyon Laser":
  type: "Weapon"
  weight: 5
  damage: 10
  slot_type: "main"
  crafting: {"asteroid.nickel_ore": 30, "asteroid.cobalt_ore": 35, "materials.laser_diodes": 15}
  crafting_duration: 40
  price: 1200
"Military Laser":
  type: "Weapon"
  weight: 10
  damage: 20
  slot_type: "main"
  crafting: {"asteroid.nickel_ore": 50, "asteroid.cobalt_ore": 80, "materials.laser_diodes": 30, "asteroid.titanium_ore": 10}
  crafting_duration: 120
  price: 2550
      
  # Hulls
"Light Hull":
  type: "Hull"
  weight: 2
  align_amplifier: 20
  slot_type: "utility"
  crafting: {"asteroid.nickel_ore": 15, "asteroid.cobalt_ore": 20, "materials.metal_plates": 15}
  crafting_duration: 25
  price: 750
"Ultralight Hull":
  type: "Hull"
  weight: 1
  align_amplifier: 30
  slot_type: "utility"
  crafting: {"asteroid.nickel_ore": 25, "asteroid.cobalt_ore": 30, "materials.metal_plates": 30}
  crafting_duration: 40
  price: 1350
      
  # Sensors
"Small Sensor":
  type: "Sensor"
  weight: 2
  target_amplifier: 20
  slot_type: "utility"
  crafting: {"asteroid.iron_ore": 25, "asteroid.cobalt_ore": 10, "materials.sensor_electronics": 30}
  crafting_duration: 40
  price: 1200
"Try Pyon Sensor":
  type: "Sensor"
  weight: 2
  target_amplifier: 30
  slot_type: "utility"
  crafting: {"asteroid.iron_ore": 50, "asteroid.cobalt_ore": 15, "materials.sensor_electronics": 50}
  crafting_duration: 70
  price: 2100
      
"Basic Scanner":
  type: "Scanner"
  weight: 2
  scanner_range: 1
  slot_type: "main"
  crafting: {"asteroid.iron_ore": 25, "asteroid.cobalt_ore": 10, "materials.sensor_electronics": 30}
  crafting_duration: 50
  price: 1200
"Advanced Scanner":
  type: "Scanner"
  weight: 2
  scanner_range: 2
  slot_type: "main"
  crafting: {"asteroid.iron_ore": 50, "asteroid.cobalt_ore": 25, "materials.sensor_electronics": 40}
  crafting_duration: 75
  price: 1800
"Military Scanner":
  type: "Scanner"
  weight: 4
  scanner_range: 4
  slot_type: "main"
  crafting: {"asteroid.iron_ore": 90, "asteroid.cobalt_ore": 50, "materials.sensor_electronics": 65, "asteroid.titanium_ore": 10}
  crafting_duration: 150
  price: 3300
"Deepspace Scanner":
  type: "Scanner"
  weight: 10
  scanner_range: 10
  slot_type: "main"
  crafting: {"asteroid.iron_ore": 900, "asteroid.cobalt_ore": 500, "materials.sensor_electronics": 650, "asteroid.titanium_ore": 100}
  crafting_duration: 1000
  price: 33000
      
  # Directional Scanners
"Directional Scanner":
  type: "Directional Scanner"
  weight: 2
  slot_type: "main"
  crafting: {"asteroid.iron_ore": 2500, "materials.sensor_electronics": 1500}
  crafting_duration: 250
  price: 75000
      
  # Warp Disruptors
"Basic Warp Disruptor":
  type: "Warp Disruptor"
  weight: 2
  disrupt_strength: 1
  slot_type: "main"
  crafting: {"asteroid.iron_ore": 25, "materials.sensor_electronics": 15}
  crafting_duration: 25
  price: 750
"Try Pyon Warp Disruptor":
  type: "Warp Disruptor"
  weight: 4
  disrupt_strength: 2
  slot_type: "main"
  crafting: {"asteroid.iron_ore": 50, "materials.sensor_electronics": 30}
  crafting_duration: 45
  price: 1350
"Military Warp Disruptor":
  type: "Warp Disruptor"
  weight: 10
  disrupt_strength: 3
  slot_type: "main"
  crafting: {"asteroid.iron_ore": 90, "materials.sensor_electronics": 30, "materials.fusion_electronics": 30, "asteroid.titanium_ore": 10}
  crafting_duration: 100
  price: 2700
  
  # Warp Core Stabilizers   
"Basic Warp Core Stabilizer":
  type: "Warp Core Stabilizer"
  weight: 2
  disrupt_immunity: 1
  slot_type: "utility"
  crafting: {"asteroid.nickel_ore": 25, "materials.fusion_electronics": 15}
  crafting_duration: 20
  price: 750
"Try Pyon Warp Core Stabilizer":
  type: "Warp Core Stabilizer"
  weight: 4
  disrupt_immunity: 2
  slot_type: "utility"
  crafting: {"asteroid.nickel_ore": 50, "materials.fusion_electronics": 45}
  crafting_duration: 60
  price: 1800
"Military Warp Core Stabilizer":
  type: "Warp Core Stabilizer"
  weight: 10
  disrupt_immunity: 3
  slot_type: "utility"
  crafting: {"asteroid.nickel_ore": 90, "materials.fusion_electronics": 60, "asteroid.titanium_ore": 10}
  crafting_duration: 80
  price: 2700
      
  # Miner
"Basic Mining Laser":
  type: "Mining Laser"
  weight: 2
  mining_amount: 1
  slot_type: "main"
  crafting: {"asteroid.nickel_ore": 5, "asteroid.iron_ore": 10, "asteroid.septarium_ore": 5}
  crafting_duration: 5
  price: 105
"Adv. Mining Laser":
  type: "Mining Laser"
  weight: 2
  mining_amount: 2
  slot_type: "main"
  crafting: {"asteroid.nickel_ore": 25, "asteroid.iron_ore": 30, "asteroid.septarium_ore": 30}
  crafting_duration: 20
  price: 450
"Core Mining Laser":
  type: "Mining Laser"
  weight: 5
  mining_amount: 3
  slot_type: "main"
  crafting: {"asteroid.nickel_ore": 90, "asteroid.iron_ore": 100, "asteroid.titanium_ore": 50}
  crafting_duration: 75
  price: 2100
      
  # Repair Bots
"Basic Repair Bot":
  name: "Basic Repair Bot"
  type: "Repair Bot"
  weight: 3
  repair_amount: 3
  slot_type: "main"
  crafting: {"asteroid.cobalt_ore": 15, "asteroid.iron_ore": 15, "materials.ai_components": 10}
  crafting_duration: 20
  price: 540
"Advanced Repair Bot":
  type: "Repair Bot"
  weight: 5
  repair_amount: 5
  slot_type: "main"
  crafting: {"asteroid.cobalt_ore": 25, "asteroid.iron_ore": 45, "materials.ai_components": 20}
  crafting_duration: 35
  price: 1050
"Colton Repair Bot":
  type: "Repair Bot"
  weight: 10
  repair_amount: 8
  slot_type: "main"
  crafting: {"asteroid.cobalt_ore": 65, "asteroid.iron_ore": 50, "materials.ai_components": 30, "asteroid.titanium_ore": 10}
  crafting_duration: 50
  price: 1650
  
  # Remote Repair Beam
"Simple Repair Beam":
  name: "Simple Repair Beam"
  type: "Repair Beam"
  weight: 3
  repair_amount: 3
  slot_type: "main"
  crafting: {"asteroid.cobalt_ore": 15, "asteroid.iron_ore": 15, "materials.ai_components": 10}
  crafting_duration: 20
  price: 540
"Advanced Repair Beam":
  type: "Repair Beam"
  weight: 5
  repair_amount: 5
  slot_type: "main"
  crafting: {"asteroid.cobalt_ore": 25, "asteroid.iron_ore": 45, "materials.ai_components": 20}
  crafting_duration: 35
  price: 1050
"Colton Repair Beam":
  type: "Repair Beam"
  weight: 10
  repair_amount: 8
  slot_type: "main"
  crafting: {"asteroid.cobalt_ore": 65, "asteroid.iron_ore": 50, "materials.ai_components": 30, "asteroid.titanium_ore": 10}
  crafting_duration: 50
  price: 1650
      
  # Defense
"Ion Shield":
  type: "Defense"
  weight: 4
  defense_amplifier: 5
  slot_type: "utility"
  crafting: {"asteroid.cobalt_ore": 15, "asteroid.nickel_ore": 15, "materials.fusion_electronics": 6}
  crafting_duration: 10
  price: 300
"Try Pyon Shield":
  type: "Defense"
  weight: 5
  defense_amplifier: 10
  slot_type: "utility"
  crafting: {"asteroid.cobalt_ore": 40, "asteroid.nickel_ore": 25, "materials.fusion_electronics": 22}
  crafting_duration: 40
  price: 1200
  
  # Storage
"Small Black Hole":
  type: "Storage"
  weight: 5
  storage_amplifier: 20
  slot_type: "utility"
  crafting: {"asteroid.iron_ore": 10, "asteroid.nickel_ore": 25, "materials.antimatter": 4}
  crafting_duration: 10
  price: 450
"Medium Black Hole":
  type: "Storage"
  weight: 10
  storage_amplifier: 30
  slot_type: "utility"
  crafting: {"asteroid.iron_ore": 20, "asteroid.nickel_ore": 45, "materials.antimatter": 10}
  crafting_duration: 30
  price: 825
"Large Black Hole":
  type: "Storage"
  weight: 20
  storage_amplifier: 40
  slot_type: "utility"
  crafting: {"asteroid.iron_ore": 20, "asteroid.nickel_ore": 40, "materials.antimatter": 50, "asteroid.titanium_ore": 10}
  crafting_duration: 70
  price: 2175
      
# Materials for Crafting
"Sensor Electronics":
  type: "Material"
  weight: 1
  price: 30
  
"Antimatter":
  type: "Material"
  weight: 1
  price: 30
    
"Fusion Electronics":
  type: "Material"
  weight: 1
  price: 30
    
"AI Components":
  type: "Material"
  weight: 1
  price: 30
    
"Metal Plates":
  type: "Material"
  weight: 1
  price: 30
    
"Laser Diodes":
  type: "Material"
  weight: 1
  price: 30