'RE-FII':   'low'
'CR-181':   'low'
'KI-233':   'low'
'ZU-6TT':   'low'
'TZ-877':   'low'
'VB-233':   'low'
'KE-35F':   'low'
'SR-378':   'low'
'KQ-43R':   'low'
'TK-63R':   'low'
'ZZ-23F':   'low'
'FH-232':   'low'
'WQ-F65':   'low'
'FT-R3T':   'low'
'NF-Z66':   'low'
'UC-233':   'low'
'Talos':    'medium'
'Decon':    'medium'
'Urus':     'medium'
'Zimse':    'medium'
'Dresi':    'medium'
'Latos':    'medium'
'Alba':     'medium'
'Odin':     'medium'
'Finid':    'medium'
'Draconis': 'medium'
'Nodens':   'medium'
'Nordar':   'medium'
'Foves': 'medium'
'Aulin':    'high'
'Hyperion': 'high'
'Komo':     'high'
'Zenais':   'high'
'Perseus':  'high'
'Pherona':  'high'
'Dau':      'high'
'Inari':    'high'
'Chanoun':  'high'
'Minin':    'high'
'Aunia':    'high'
'Joamma':   'high'
'Belinara': 'high'